# Generated by Django 4.0.6 on 2022-07-28 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Object Identifier')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('title', models.CharField(default='New Quiz', max_length=255)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ('-created_on',),
            },
        ),
    ]
