# Generated by Django 4.0.6 on 2022-07-28 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Object Identifier')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('technique', models.CharField(choices=[(0, 'Multiple Choice')], default=0, max_length=255, verbose_name='Type of Question')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(choices=[(0, 'Fundamental1'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], verbose_name='Difficulty Level')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('-created_on',),
            },
        ),
    ]
